### ISSUE TITLE
Add MAINTAINERS.md file

### ISSUE THREAD

**Issue by joewxboy** [open-horizon-services/example-achatina-monitor#5]
Please duplicate the file in https://raw.githubusercontent.com/open-horizon-services/web-helloworld-cpp/ac403917069c896f685a317f4ca6b503694f5187/MAINTAINERS.md in this repo.

**Comment by deepesh85b** [comment]
@joewxboy 
Please assign this to

**Comment by oskurtt** [comment]
can i work on this issue if it's not currently being worked on?

**Comment by joewxboy** [comment]
@oskurtt you got it
